Update action.yaml

diff --git a/gha/test/action.yaml b/gha/test/action.yaml
--- a/gha/test/action.yaml
+++ b/gha/test/action.yaml
@@ -24,6 +24,21 @@ runs:
   using: "composite"
   steps:
 
+#    - name: Get Pack Name (original)
+#      shell: bash
+#      id: pack-name
+#      env:
+#        VIRTUALENV_DIR: "~/virtualenv"
+#        ACTION_PATH: ${{ github.action_path }}
+#      run: |
+#        env
+#        export PACK_NAME=$(${{env.VIRTUALENV_DIR}}/bin/python ${ACTION_PATH}/../../.circle/validate.py "${GITHUB_REPOSITORY##*/}" pack.yaml)
+#        if [[ -z "${PACK_NAME}" ]]; then
+#        echo "Unable to retrieve pack name."
+#        exit 1
+#        fi
+#        echo "::set-output name=pack-name::${PACK_NAME}"
+
     - name: Get Pack Name
       shell: bash
       id: pack-name
@@ -32,7 +47,7 @@ runs:
         ACTION_PATH: ${{ github.action_path }}
       run: |
         env
-        export PACK_NAME=$(${{env.VIRTUALENV_DIR}}/bin/python ${ACTION_PATH}/../../.circle/validate.py "${GITHUB_REPOSITORY##*/}" pack.yaml)
+        export PACK_NAME=$(${{env.VIRTUALENV_DIR}}/bin/python ${ACTION_PATH}/../../.circle/validate.py "logicmonitor-stackstorm-pack##*/" pack.yaml)
         if [[ -z "${PACK_NAME}" ]]; then
         echo "Unable to retrieve pack name."
         exit 1
