Ignore gha failures on python not supported by pack

diff --git a/.github/actions/py-dependencies/action.yaml b/.github/actions/py-dependencies/action.yaml
--- a/.github/actions/py-dependencies/action.yaml
+++ b/.github/actions/py-dependencies/action.yaml
@@ -114,14 +114,15 @@ runs:
       shell: bash
       working-directory: pack
       run: |
-        export PACK_PYTHON_VERSIONS=$(${VIRTUALENV_DIR}/bin/python ${CI_DIR}/utils/extract_from_yaml.py pack.yaml python_versions)
-        export PACK_PYTHON_SUPPORTED=$(echo ${PACK_PYTHON_VERSIONS} | jq 'any(.[]; . == "${{ inputs.python-version-short[0] }}")')
+        PY_V=$(echo ${{ inputs.python-version }} | cut -c1)
+        PACK_PYTHON_VERSIONS=$(${VIRTUALENV_DIR}/bin/python ${CI_DIR}/utils/extract_from_yaml.py pack.yaml python_versions)
+        PACK_SUPPORTS_PYTHON_VERSION=$(echo ${PACK_PYTHON_VERSIONS} | jq -r 'any(.[]; . == "'${PY_V}'")')
         echo "PACK_PYTHON_VERSIONS=${PACK_PYTHON_VERSIONS}" | tee -a ${GITHUB_ENV}
-        echo "PACK_PYTHON_SUPPORTED=${PACK_PYTHON_SUPPORTED}" | tee -a ${GITHUB_ENV}
+        echo "PACK_SUPPORTS_PYTHON_VERSION=${PACK_SUPPORTS_PYTHON_VERSION}" | tee -a ${GITHUB_ENV}
+        echo "PYTHON_MAJOR_VERSION=${PY_V}" | tee -a ${GITHUB_ENV}
 
     - name: Install Pack Requirements
       if: inputs.mode == 'pack'
-      # continue if pack does not support this version of python
       shell: bash
       working-directory: pack
       env:
@@ -131,11 +132,25 @@ runs:
         echo "::group::Install Pack Requirements"
         if [[ -f "${PACK_REQUIREMENTS_FILE}" ]]; then
           echo "Installing pack requirements from ${PACK_REQUIREMENTS_FILE}"
-          ${VIRTUALENV_DIR}/bin/pip install -r "${PACK_REQUIREMENTS_FILE}"
+          if ! ${VIRTUALENV_DIR}/bin/pip install -r "${PACK_REQUIREMENTS_FILE}"; then
+            rc=$?
+            if [[ "true" == "${PACK_SUPPORTS_PYTHON_VERSION}" ]]; then
+              exit $rc
+            else
+              echo "Ignoring failures since pack doesn't declare Python ${PYTHON_MAJOR_VERSION} support in pack.yaml"
+            fi
+          fi
         fi
         if [[ -f "${PACK_TESTS_REQUIREMENTS_FILE}" ]]; then
           echo "Installing pack tests requirements from ${PACK_TESTS_REQUIREMENTS_FILE}"
-          ${VIRTUALENV_DIR}/bin/pip install -r "${PACK_TESTS_REQUIREMENTS_FILE}"
+          if ! ${VIRTUALENV_DIR}/bin/pip install -r "${PACK_TESTS_REQUIREMENTS_FILE}"; then
+            rc=$?
+            if [[ "true" == "${PACK_SUPPORTS_PYTHON_VERSION}" ]]; then
+              exit $rc
+            else
+              echo "Ignoring failures since pack doesn't declare Python ${PYTHON_MAJOR_VERSION} support in pack.yaml"
+            fi
+          fi
         fi
         echo "::endgroup::"
 
diff --git a/.github/actions/test/action.yaml b/.github/actions/test/action.yaml
--- a/.github/actions/test/action.yaml
+++ b/.github/actions/test/action.yaml
@@ -15,10 +15,6 @@ inputs:
       see: https://docs.stackstorm.com/reference/sharing_code_sensors_actions.html
     default: false
     required: false
-  python-version-short:
-    description: Which python version we are testing with (defaults to 3.6)
-    default: "3.6"
-    required: false
 
 outputs:
   pack-name:
@@ -65,12 +61,17 @@ runs:
         echo "ST2_INSTALL_DEPS=0" >> ${GITHUB_ENV}
 
     - name: Run tests
-      # continue if pack does not support this version of python
-      #continue-on-error: ${{ ! contains(fromJSON(env.PACK_PYTHON_VERSIONS), inputs.python-version-short[0]) }}
       shell: bash
       # NB: This Makefile has CircleCI-based defaults which we override with env vars
       # defined in the various composite actions.
       run: |
         source ${VIRTUALENV_DIR}/bin/activate
         # NB: tests require services (mongo, rabbitmq) which must be defined by the calling workflow
-        make -C "${ROOT_DIR}" -f "${CI_DIR}/.circle/Makefile" all-ci
+        if ! make -C "${ROOT_DIR}" -f "${CI_DIR}/.circle/Makefile" all-ci; then
+          rc=$?
+          if [[ "true" == "${PACK_SUPPORTS_PYTHON_VERSION}" ]]; then
+            exit $rc
+          else
+            echo "Ignoring failures since pack doesn't declare Python ${PYTHON_MAJOR_VERSION} support in pack.yaml"
+          fi
+        fi
