Update index-update.yaml

diff --git a/.github/workflows/index-update.yaml b/.github/workflows/index-update.yaml
--- a/.github/workflows/index-update.yaml
+++ b/.github/workflows/index-update.yaml
@@ -174,20 +174,29 @@ jobs:
           ####################################
           # CHECK IF PACK HAS A PACK.YAML FILE
           ####################################
+
+            echo "$FILE exists."
+          else 
+            echo "$FILE does not exist."
+          fi
           #if ! [ -f "./pack.yaml"] || ["${repo_name}"==["test"||"test_content_version"]] ; then
-          if ! [ -f "./pack.yaml"] ; then
-            cd ..
-            rm -rf ${repo_name}
-            echo "DELETED clone of ${PACKS_ORG}/${repo_name}: missing pack.yaml"
-            echo "${PACKS_ORG}/${repo_name}" >> ${GITHUB_WORKSPACE}/bad_pack_repos
-          else
-            echo -e "\npwd:\n" #DEBUG
+          #if ! [ -f "./pack.yaml"] ; then
+          echo "lsing in directory"
+          ls
+          FILE=./pack.yaml
+          if [ -f "$FILE" ]; then
             pwd
             echo -e "\ncd..\n" #DEBUG
             cd ..
             echo -e "\npwd:\n" #DEBUG
             pwd
             echo -e "\nls:\n`ls`\n" #DEBUG
+          else
+            cd ..
+            rm -rf ${repo_name}
+            echo "DELETED clone of ${PACKS_ORG}/${repo_name}: missing pack.yaml"
+            echo "${PACKS_ORG}/${repo_name}" >> ${GITHUB_WORKSPACE}/bad_pack_repos
+            echo -e "\npwd:\n" #DEBUG
           fi
         done
 
