Update index-update.yaml

diff --git a/.github/workflows/index-update.yaml b/.github/workflows/index-update.yaml
--- a/.github/workflows/index-update.yaml
+++ b/.github/workflows/index-update.yaml
@@ -179,19 +179,15 @@ jobs:
           echo "lsing in directory"
           ls
           FILE=./pack.yaml
-          if [ -f "$FILE" ] && ["${repo_name}"!="test"] && ["${repo_name}"=="test_content_version"]; then
-            pwd
-            echo -e "\ncd..\n" #DEBUG
-            cd ..
-            echo -e "\npwd:\n" #DEBUG
-            pwd
-            echo -e "\nls:\n`ls`\n" #DEBUG
-          else
+          if ! [ -f "$FILE" ] || ["${repo_name}" == "test"] || ["${repo_name}" != "test_content_version"]; then
+            # DELETE PACK
             cd ..
             rm -rf ${repo_name}
-            echo "DELETED clone of ${PACKS_ORG}/${repo_name}: missing pack.yaml"
+            echo "DELETED clone of ${PACKS_ORG}/${repo_name}: missing pack.yaml OR pack is named 'test' or 'test_content_version'"
             echo "${PACKS_ORG}/${repo_name}" >> ${GITHUB_WORKSPACE}/bad_pack_repos
-            echo -e "\npwd:\n" #DEBUG
+          else
+            # PACK STAYS
+            echo ${repo_name} IS VALID!
           fi
         done
 
